language: java

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true

script: mvn -DskipTests=true clean install

after_success:
  - mvn clean test cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)


branches:
  only:
    - master